version: "3.7"

services:
  web:
    build:
      context: .
    volumes:
      - "./.hoppscotch:/app/.hoppscotch"
      - "./assets:/app/assets"
      - "./directives:/app/directives"
      - "./layouts:/app/layouts"
      - "./middleware:/app/middleware"
      - "./pages:/app/pages"
      - "./plugins:/app/plugins"
      - "./static:/app/static"
      - "./store:/app/store"
      - "./components:/app/components"
      - "./helpers:/app/helpers"
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      VITE_API_KEY : ""
      VITE_AUTH_DOMAIN : ""
      VITE_DATABASE_URL : ""
      VITE_PROJECT_ID : ""
      VITE_STORAGE_BUCKET : ""
      VITE_MESSAGING_SENDER_ID : ""
      VITE_APP_ID : ""
      VITE_MEASUREMENT_ID : ""
      VITE_BACKEND_GQL_URL : "http://localhost:8989/graphql"
      VITE_BACKEND_WS_URL : "wss://localhost:8989/graphql"
    command: "pnpm run start"
